/**
 * The words the game may SHOW - the allowlist, and whether it is fit to ask a
 * puzzle from.
 *
 * `puzzleWords.ts` exists because four of BONUS's five bonus screens put a word
 * on the screen, and `words.ts` may never be the source of one (NOTICE.md: "the
 * moment anything displays a dictionary word ... that surface must draw from an
 * affirmative allowlist"). This file is what stops that guarantee decaying: an
 * allowlist can be quietly regenerated from the dictionary, quietly drift out of
 * it, or quietly be trimmed below the size the puzzles need, and none of those
 * three breaks anything visibly.
 */
import { readFileSync } from "node:fs";
import { describe, it, expect } from "vitest";
import { PUZZLE_WORDS, PUZZLE_BY_LENGTH } from "./puzzleWords";
import { WORDS } from "./words";

const SRC = readFileSync(new URL("./puzzleWords.ts", import.meta.url), "utf8");
const AZ = "abcdefghijklmnopqrstuvwxyz".split("");
const blank = (w: string, i: number) => `${w.slice(0, i)}_${w.slice(i + 1)}`;
const fill = (p: string, c: string) => p.replace("_", c);
/** Every letter that turns this pattern into a real word, per the DICTIONARY. */
const solvers = (...ps: string[]) => AZ.filter((c) => ps.every((p) => WORDS.has(fill(p, c))));

describe("the pool is real", () => {
  /**
   * THE CONTROL, first, because almost everything below is "no entry fails X"
   * and an empty pool passes every one of those. It also proves `WORDS` loaded,
   * which the subset test underneath depends on entirely - a `WORDS` that is
   * empty makes "every puzzle word is in the dictionary" fail loudly, but a
   * `WORDS` that is somehow everything makes it pass vacuously.
   */
  it("has words in it, and the dictionary has words in it", () => {
    expect(PUZZLE_WORDS.length).toBeGreaterThan(250);
    expect(WORDS.size).toBeGreaterThan(20000);
    expect(WORDS.has("cat")).toBe(true);
    expect(WORDS.has("zzzzzz")).toBe(false);
  });

  it("is all lowercase letters, 3 to 6 long", () => {
    const bad = PUZZLE_WORDS.filter((w) => !/^[a-z]{3,6}$/.test(w));
    expect(bad, `not a plain 3-6 letter word: ${bad.join(" ")}`).toEqual([]);
  });

  it("says nothing twice", () => {
    const seen = new Set<string>();
    const dup = PUZZLE_WORDS.filter((w) => (seen.has(w) ? true : (seen.add(w), false)));
    expect(dup, `duplicated: ${dup.join(" ")}`).toEqual([]);
  });
});

describe("rule 2 - every word it may show, the board will also accept", () => {
  /**
   * A bonus round that teaches a child a word, followed by a board that refuses
   * to score it, is worse than not having taught them. This is also the check
   * that caught `knife`: absent from ENABLE's mirror while `knifed`, `knifer`
   * and `knifes` are all present.
   */
  it("is a subset of the dictionary", () => {
    const missing = PUZZLE_WORDS.filter((w) => !WORDS.has(w));
    expect(missing, `shown but not accepted on the board: ${missing.join(" ")}`).toEqual([]);
  });
});

describe("rule 1 - authored, never derived", () => {
  /**
   * The load-bearing one. An allowlist filtered out of the dictionary IS the
   * dictionary, and inherits every gap in a blocklist that is documented as
   * incomplete. Nothing here may import `words.ts` and nothing may generate this
   * file, so a change to it is a change somebody wrote and somebody can read.
   */
  const IMPORTS_DICT = /^\s*import[^;]*from\s+["'][^"']*words["']/m;
  const GENERATED = /^\/\/ GENERATED by/m;

  it("does not read the dictionary", () => {
    expect(SRC, "puzzleWords.ts imports the dictionary").not.toMatch(IMPORTS_DICT);
    // The control. Both assertions in this describe are about a string being
    // ABSENT, and an absent string is also what a matcher that can never fire
    // reports - so each one is run against something it must catch.
    expect('import { WORDS } from "./words";').toMatch(IMPORTS_DICT);
  });

  it("is not generated by a script", () => {
    expect(SRC, "carries a GENERATED banner").not.toMatch(GENERATED);
    // ...and the file that IS generated says so on its first line. The prose in
    // puzzleWords.ts uses the word "generated" about the dictionary, which is
    // why this matches the BANNER rather than the word.
    expect(readFileSync(new URL("./words.ts", import.meta.url), "utf8")).toMatch(GENERATED);
  });
});

describe("rule 3 - it can be audited by reading", () => {
  it("is grouped under labels", () => {
    const labels = [...SRC.matchAll(/^ {2}\/\/ (.+)$/gm)].map((m) => m[1]);
    expect(labels.length, `only ${labels.length} groups - the sweep may be blind`).toBeGreaterThan(10);
  });

  /**
   * Nothing from the dictionary's own blocklist, and nothing containing one of
   * the substrings that are never innocent. It is a NET under an authored list
   * rather than the safety mechanism - the safety mechanism is that a human
   * wrote every line - but a net costs nothing and a typo is a real way in.
   */
  it("carries nothing from the blocked substrings", () => {
    const SUBSTRINGS = ["fuck", "cunt", "nigg", "shit", "bitch", "whore", "rapist", "faggot"];
    const hits = PUZZLE_WORDS.filter((w) => SUBSTRINGS.some((s) => w.includes(s)));
    expect(hits, `blocked: ${hits.join(" ")}`).toEqual([]);
    // The control - the matcher must be able to fire at all.
    expect(["kitten", "shitake"].filter((w) => SUBSTRINGS.some((s) => w.includes(s)))).toEqual(["shitake"]);
  });
});

/**
 * IS THIS POOL FIT TO ASK BONUS'S QUESTIONS FROM?
 *
 * Measured here rather than assumed, because the answer decides whether the four
 * remaining bonus screens can be built from this file at all - and it is cheaper
 * to find out now than after one is written. Every count below was measured on
 * 2026-08-25 and the floors are set well under what was found, so this asserts
 * the pool stays fit rather than pinning today's exact number
 * (a-threshold-tuned-against-todays-tree-goes-stale.md).
 *
 * These brute-force what a generator will later do properly. That is deliberate
 * and it is the one thing to remember when the generators arrive: this is a
 * fitness check on the POOL, and the game's own logic gets its own tests. Two
 * implementations of "is this puzzle solvable" agreeing is worth nothing if the
 * second one is a copy of the first.
 */
describe("the pool can ask BONUS's questions", () => {
  /**
   * THE DISCRIMINATION CONTROL, and it runs first. Every count below is "how
   * many patterns have exactly one answer", and a `solvers` that returned one
   * letter for everything would report a perfect pool. `_at` and `_ow` are both
   * wide open, so their pair must be too.
   */
  it("can tell an ambiguous pattern from a settled one", () => {
    expect(solvers("_at").length, "_at should be wide open").toBeGreaterThan(5);
    expect(solvers("_at", "_ow").length, "_at + _ow is not a puzzle, it is a guess").toBeGreaterThan(3);
    expect(solvers("_at", "_amel"), "only a c makes both").toEqual(["c"]);
  });

  /** "Complete the missing letters in the word before you." Measured: 499. */
  it("has enough one-blank words with a single answer", () => {
    let n = 0;
    for (const w of PUZZLE_WORDS) for (let i = 0; i < w.length; i++) {
      if (solvers(blank(w, i)).length === 1) n++;
    }
    expect(n, `only ${n} fill-the-gap puzzles have one answer`).toBeGreaterThan(300);
  });

  /**
   * "The identical letter, missing in the two words before you." Measured on the
   * same day: 48,708 pairs out of 60,859 tried, so this floor is not close.
   */
  it("has pairs of words sharing exactly one possible missing letter", () => {
    const byLetter = new Map<string, string[]>();
    for (const w of PUZZLE_WORDS) for (let i = 0; i < w.length; i++) {
      const c = w[i];
      (byLetter.get(c) ?? byLetter.set(c, []).get(c)!).push(blank(w, i));
    }
    let n = 0;
    for (const [c, ps] of byLetter) {
      for (let a = 0; a < ps.length; a++) for (let b = a + 1; b < ps.length; b++) {
        const only = solvers(ps[a], ps[b]);
        if (only.length === 1 && only[0] === c) n++;
      }
    }
    expect(n, `only ${n} two-word puzzles have one answer`).toBeGreaterThan(2000);
  });

  /** Every length a screen might ask for is actually stocked. */
  it("is stocked at every length", () => {
    for (const len of [3, 4, 5, 6]) {
      expect(PUZZLE_BY_LENGTH.get(len)?.length ?? 0, `${len}-letter words`).toBeGreaterThan(20);
    }
    expect([...PUZZLE_BY_LENGTH.keys()].sort()).toEqual([3, 4, 5, 6]);
  });
});
